name: CD - Deploy to NCP

on:
  workflow_run:
    workflows: ['CI - Build and Push']
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ACG_RULE_FORMAT: "protocolTypeCode='TCP',ipBlock='GITHUB_IP/32',portRange='22'"

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          script: |
            cd ~/projects/web06-locus
            git fetch origin develop
            git checkout -f develop
            git pull origin develop

            echo "${{ secrets.DEV_ENV_PROD }}" > .env.prod
            docker login ${{ secrets.DEV_REGISTRY }} -u ${{ secrets.NCP_ACCESS_KEY }} -p ${{ secrets.NCP_SECRET_KEY }}
            docker compose pull
            docker compose up -d
            docker image prune -f
            docker compose exec -T locus-api pnpm --filter @locus/api exec prisma db push --accept-data-loss
      - name: Remove Github Action IP from ACG
        if: always()
        run: |
          sleep 10

          cd CLI_*/cli_linux
          RULE=$(echo "${{ env.ACG_RULE_FORMAT }}" | sed "s/GITHUB_IP/${{ steps.ip.outputs.public_ip }}/")

          ./ncloud vserver removeAccessControlGroupInboundRule \
            --regionCode KR \
            --vpcNo "${{ secrets.NCP_VPC_ID }}" \
            --accessControlGroupNo "${{ secrets.NCP_ACG_ID }}" \
            --accessControlGroupRuleList "$RULE"

      - name: Remove Github Action IP from ACG (Post-action)
        if: always()
        run: |
          sleep 10

          cd CLI_*/cli_linux
          RULE="protocolTypeCode='TCP',ipBlock='${{ steps.ip.outputs.public_ip }}/32',portRange='22'"
          
          ./ncloud vserver removeAccessControlGroupInboundRule \
            --regionCode KR \
            --vpcNo "${{ secrets.NCP_VPC_ID }}" \
            --accessControlGroupNo "${{ secrets.NCP_ACG_ID }}" \
            --accessControlGroupRuleList "$RULE"